# Generated by Django 5.2.9 on 2026-03-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationnode',
            name='max_output_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationnode',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversationnode',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationnode',
            name='top_p',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
