# Generated by Django 5.2.9 on 2026-04-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0002_conversationnode_max_output_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('workspace', 'Workspace'), ('branch', 'Branch')], default='workspace', max_length=20)),
                ('memory_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('summary', 'Summary'), ('task', 'Task'), ('artifact', 'Artifact')], default='fact', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('pinned', 'Pinned'), ('extracted', 'Extracted')], default='manual', max_length=20)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_anchor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anchored_memories', to='tree_ui.conversationnode')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='tree_ui.nodemessage')),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_memories', to='tree_ui.conversationnode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='tree_ui.workspace')),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at', '-created_at'],
            },
        ),
    ]
