# Generated by Django 5.2.9 on 2026-04-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0003_conversationmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image')], default='image', max_length=20)),
                ('file', models.FileField(upload_to='node_attachments/%Y/%m/%d')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tree_ui.conversationnode')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
