# Generated by Django 5.2.9 on 2026-04-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0006_nodeattachment_pdf_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationnode',
            name='routing_decision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversationnode',
            name='routing_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto-fast', 'Auto Fast'), ('auto-balanced', 'Auto Balanced'), ('auto-quality', 'Auto Quality')], default='manual', max_length=20),
        ),
    ]
