# Generated by Django 5.2.9 on 2026-04-14 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0007_conversationnode_routing_decision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=120)),
                ('tool_type', models.CharField(default='internal', max_length=40)),
                ('invocation_payload', models.TextField(blank=True)),
                ('result_payload', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_invocations', to='tree_ui.conversationnode')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
