# Generated by Django 5.2.9 on 2026-04-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0008_toolinvocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCPSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source_id', models.SlugField(max_length=120, unique=True)),
                ('source_type', models.CharField(choices=[('internal', 'Internal Registry'), ('mcp_server', 'Remote MCP Server'), ('mock', 'Mock/Placeholder Source')], default='mcp_server', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCP Source',
                'verbose_name_plural': 'MCP Sources',
                'ordering': ['created_at'],
            },
        ),
    ]
