# Generated by Django 5.2.9 on 2026-04-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0009_mcpsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinvocation',
            name='source_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
