# Generated by Django 5.2.9 on 2026-04-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_ui', '0010_toolinvocation_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpsource',
            name='last_check_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mcpsource',
            name='last_check_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcpsource',
            name='last_check_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcpsource',
            name='last_check_tool_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcpsource',
            name='last_check_tools_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mcpsource',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
