# Generated by Django 5.2.9 on 2026-04-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree_ui", "0011_mcpsource_last_check_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpsource",
            name="last_check_client_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="mcpsource",
            name="last_check_last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mcpsource",
            name="last_check_message_endpoint",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mcpsource",
            name="last_check_transport",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
