# Generated by Django 5.2.9 on 2026-04-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tree_ui", "0012_mcpsource_last_check_transport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPSourceCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ok", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(blank=True)),
                ("tool_count", models.PositiveIntegerField(default=0)),
                ("tool_names_summary", models.TextField(blank=True)),
                ("transport", models.CharField(blank=True, max_length=40)),
                ("client_status", models.CharField(blank=True, max_length=40)),
                ("message_endpoint", models.TextField(blank=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="checks", to="tree_ui.mcpsource")),
            ],
            options={
                "verbose_name": "MCP Source Check",
                "verbose_name_plural": "MCP Source Checks",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
